### ISSUE TITLE
Remove "Default" requirement from PortSpec 

### ISSUE THREAD

**Issue by yuval-k** [RustAudio/rust-jack#66]
Hi,

What's the reason that PortSpec is defined with a requirement for *Default* like so:
```pub unsafe trait PortSpec: Default + Sized {```

Can the requirement it be removed? 
The existing portspecs can have their defaults of course, so this change is backward compatible.

 I am trying to use jack with a custom port type that needs to be initialized dynamically at runtime.

**Comment by wmedrano** [comment]
The requirement doesn't serve a functional purpose, so it can be removed.

My thought with this was that people would look at docs for PortSpec, see it has default, and then they could just try out default for any Port for some quick prototyping.

However, since it doesn't make sense to have a default for all port types, the constraint should be removed.

**Comment by yuval-k** [comment]
Same goes for the 'static requirement here:
```fn jack_port_type(&self) -> &'static str```

that was a string inside the object can be used.

If you'de like i can create a PR tonight..

**Comment by wmedrano** [comment]
Sounds good.

**Comment by wmedrano** [comment]
Closed by #68
